* Include all macros from GitHub;
filename cml  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_cml.sas';
filename dat  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_data.sas';
filename eta  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_etatemp.sas';
filename gam  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_gamma.sas';
filename cfit url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_itemcfit.sas';
filename fit  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_itemfit.sas';
filename mml  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_mml.sas';
filename pp   url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_ppar.sas';
filename pw   url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_PW.sas';
filename psi  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_PSI.sas';
filename sim  url 'https://raw.githubusercontent.com/KarlBangChristensen/Rasch/master/rasch_simu.sas';
%include cml;
%include dat;
%include eta;
%include gam;
%include cfit;
%include fit;
%include mml;
%include pp;
%include pw;
%include psi;
%include sim;
